// packages/angular/src/components/field-overlay.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  OnDestroy,
  AfterViewInit,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import type { FieldDef, SignerDef } from '@pdf-sign/core'
import type { DragEngine } from '@pdf-sign/core'
import type { RenderPageResult } from '@pdf-sign/core'
import { FieldChipComponent } from './field-chip.component.js'

@Component({
  selector: 'pdf-field-overlay',
  standalone: true,
  imports: [CommonModule, FieldChipComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      #overlayEl
      class="pointer-events-auto absolute inset-0"
      [style.z-index]="'var(--psign-z-overlay)'"
    >
      <pdf-field-chip
        *ngFor="let field of visibleFields; trackBy: trackById"
        [field]="field"
        [signers]="signers"
        [viewport]="viewport"
        [dragEngine]="dragEngine"
        [isSelected]="selectedFieldId === field.id"
        [isComplete]="completedSet.has(field.id)"
        [mode]="mode"
        (select)="fieldSelect.emit($event)"
        (delete)="fieldDelete.emit($event)"
      />
    </div>
  `,
})
export class FieldOverlayComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() fields: FieldDef[] = []
  @Input() signers: SignerDef[] = []
  @Input() page = 0
  @Input() viewport: RenderPageResult['viewport'] | null = null
  @Input() dragEngine: DragEngine | null = null
  @Input() selectedFieldId: string | null = null
  @Input() mode: 'prepare' | 'sign' | 'readonly' = 'prepare'
  @Input() completedFieldIds: string[] = []

  @Output() fieldSelect = new EventEmitter<string>()
  @Output() fieldDelete = new EventEmitter<string>()

  @ViewChild('overlayEl') overlayElRef?: ElementRef<HTMLElement>

  private cleanupOverlay: (() => void) | null = null

  get visibleFields(): FieldDef[] {
    return this.fields.filter((f) => f.rect.page === this.page)
  }

  get completedSet(): Set<string> {
    return new Set(this.completedFieldIds)
  }

  trackById(_: number, field: FieldDef): string {
    return field.id
  }

  ngAfterViewInit(): void {
    this.registerOverlay()
  }

  ngOnChanges(): void {
    if (this.overlayElRef) this.registerOverlay()
  }

  private registerOverlay(): void {
    this.cleanupOverlay?.()
    if (!this.dragEngine || !this.overlayElRef) return
    this.cleanupOverlay = this.dragEngine.registerOverlay(
      this.overlayElRef.nativeElement,
      this.page,
    )
  }

  ngOnDestroy(): void {
    this.cleanupOverlay?.()
  }
}

// packages/vue/src/components/FieldOverlay.vue
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed } from 'vue'
import type { FieldDef, SignerDef } from '@pdf-sign/core'
import type { DragEngine } from '@pdf-sign/core'
import type { RenderPageResult } from '@pdf-sign/core'
import FieldChip from './FieldChip.vue'

interface Props {
  fields: FieldDef[]
  signers: SignerDef[]
  page: number
  viewport: RenderPageResult['viewport'] | null
  dragEngine: DragEngine | null
  selectedFieldId?: string | null
  mode: 'prepare' | 'sign' | 'readonly'
  completedFieldIds?: string[]
}

const props = withDefaults(defineProps<Props>(), {
  selectedFieldId: null,
  completedFieldIds: () => [],
})

const emit = defineEmits<{
  'field-select': [fieldId: string]
  'field-delete': [fieldId: string]
  'overlay-click': [{ x: number; y: number }]
}>()

const overlayEl = ref<HTMLElement | null>(null)
let cleanupOverlay: (() => void) | null = null

function registerOverlay() {
  cleanupOverlay?.()
  if (!props.dragEngine || !overlayEl.value) return
  cleanupOverlay = props.dragEngine.registerOverlay(overlayEl.value, props.page)
}

onMounted(() => registerOverlay())

watch(
  () => [props.dragEngine, props.page] as const,
  () => registerOverlay(),
)

onUnmounted(() => cleanupOverlay?.())

const visibleFields = computed(() =>
  props.fields.filter((f) => f.rect.page === props.page),
)

function handleOverlayClick(e: MouseEvent) {
  if (e.target === overlayEl.value) {
    emit('overlay-click', { x: e.offsetX, y: e.offsetY })
  }
}

const completedSet = computed(() => new Set(props.completedFieldIds))
</script>

<template>
  <div
    ref="overlayEl"
    class="pointer-events-auto absolute inset-0"
    :style="{ zIndex: 'var(--psign-z-overlay)' }"
    @click="handleOverlayClick"
  >
    <FieldChip
      v-for="field in visibleFields"
      :key="field.id"
      :field="field"
      :signers="signers"
      :viewport="viewport"
      :drag-engine="dragEngine"
      :is-selected="selectedFieldId === field.id"
      :is-complete="completedSet.has(field.id)"
      :mode="mode"
      @select="(id) => emit('field-select', id)"
      @delete="(id) => emit('field-delete', id)"
    />
  </div>
</template>
