// packages/vue/src/components/PdfSigner.vue
<script setup lang="ts">
import {
  ref,
  computed,
  onMounted,
  onUnmounted,
  watch,
} from 'vue'
import type {
  PdfSignOptions,
  FieldDef,
  SignerDef,
  PdfTemplate,
  SigningResult,
  ThemeTokens,
  AuditEntry,
} from '@pdf-sign/core'
import {
  injectTheme,
  removeTheme,
  overlayToPdf,
  overlayDimensionsToPdf,
  clampToPdfPage,
  DragEngine,
  PdfExporter,
} from '@pdf-sign/core'
import type { RenderPageResult } from '@pdf-sign/core'
import { usePdfSign } from '../composables/usePdfSign.js'
import ToolBar from './ToolBar.vue'
import PdfViewer from './PdfViewer.vue'
import FieldPalette from './FieldPalette.vue'
import SignatureModal from './SignatureModal.vue'
import FieldPropertiesPanel from './FieldPropertiesPanel.vue'

// ── Props ─────────────────────────────────────────────────────────────────

interface Props {
  pdf?: PdfSignOptions['pdf']
  mode?: PdfSignOptions['mode']
  template?: PdfTemplate
  signerId?: string
  signers?: SignerDef[]
  theme?: Partial<ThemeTokens>
  includeAuditPage?: boolean
  snapGrid?: number
}

const props = withDefaults(defineProps<Props>(), {
  pdf: null,
  mode: 'prepare',
  includeAuditPage: true,
  snapGrid: 0,
})

// ── Emits ─────────────────────────────────────────────────────────────────

const emit = defineEmits<{
  'template-ready': [template: PdfTemplate]
  'fields-changed': [fields: FieldDef[]]
  'signing-complete': [result: SigningResult]
  'declined': [payload: { signerId: string; reason: string; timestamp: string }]
  'export-ready': [payload: { pdfBytes: Uint8Array; filename: string }]
  'error': [payload: { message: string; cause?: unknown }]
}>()

// ── Root element ref (for theme injection) ────────────────────────────────

const rootEl = ref<HTMLElement | null>(null)

watch(
  () => props.theme,
  (theme) => {
    if (!rootEl.value) return
    if (theme) injectTheme(rootEl.value, theme)
    else removeTheme(rootEl.value)
  },
  { immediate: false, deep: true },
)

onMounted(() => {
  if (rootEl.value && props.theme) injectTheme(rootEl.value, props.theme)
})

onUnmounted(() => {
  if (rootEl.value) removeTheme(rootEl.value)
})

// ── Core controller ───────────────────────────────────────────────────────

const {
  fields,
  signers: controllerSigners,
  pageCount,
  canUndo,
  canRedo,
  isLoading,
  hasError,
  signingProgress,
  load,
  setPageCount,
  startEditing,
  addField,
  updateField,
  moveField,
  deleteField,
  undo,
  redo,
  buildTemplate,
  completeField,
  pendingFields,
  decline,
  submit,
  controller,
} = usePdfSign({
  mode: props.mode,
  pdf: props.pdf,
  includeAuditPage: props.includeAuditPage,
  ...(props.template !== undefined && { template: props.template }),
  ...(props.signerId !== undefined && { signerId: props.signerId }),
  ...(props.signers !== undefined && { signers: props.signers }),
})

// Wire controller events to component emits
onMounted(() => {
  controller.events.on('fields-changed', ({ fields: f }) => emit('fields-changed', f))
  controller.events.on('template-ready', ({ template }) => emit('template-ready', template))
  controller.events.on('signing-complete', (result) => emit('signing-complete', result))
  controller.events.on('declined', (payload) => emit('declined', payload))
  controller.events.on('export-ready', (payload) => emit('export-ready', payload))
  controller.events.on('error', (payload) => emit('error', payload))
})

// ── Local UI state ────────────────────────────────────────────────────────

const currentPage = ref(0)
const selectedFieldId = ref<string | null>(null)
const currentViewport = ref<RenderPageResult['viewport'] | null>(null)
const activeSignerIdForPalette = ref<string | null>(
  props.signers?.[0]?.id ?? 'signer-1',
)
const viewerRef = ref<InstanceType<typeof PdfViewer> | null>(null)
const showSignatureModal = ref(false)
const pendingSignatureFieldId = ref<string | null>(null)
const completedFieldIds = ref<string[]>([])

const displaySigners = computed(() => controllerSigners.value)

const selectedField = computed(
  () => fields.value.find((f) => f.id === selectedFieldId.value) ?? null,
)

// ── Drag engine ───────────────────────────────────────────────────────────

const dragEngine = new DragEngine({ gridSize: props.snapGrid })

onUnmounted(() => dragEngine.destroy())

dragEngine.on('palette-drop', ({ fieldTypeId, overlayX, overlayY, page }) => {
  if (!currentViewport.value) return

  const DEFAULT_FIELD_SIZES: Record<string, { w: number; h: number }> = {
    signature: { w: 180, h: 60 },
    initials:  { w: 80,  h: 40 },
    stamp:     { w: 100, h: 100 },
    checkbox:  { w: 20,  h: 20 },
    radio:     { w: 16,  h: 16 },
    default:   { w: 150, h: 36 },
  }
  const { w: defaultW, h: defaultH } =
    DEFAULT_FIELD_SIZES[fieldTypeId] ?? DEFAULT_FIELD_SIZES['default']!

  const vp = currentViewport.value
  const halfWPx = (defaultW / vp.pdfNaturalWidth) * vp.cssWidth / 2
  const halfHPx = (defaultH / vp.pdfNaturalHeight) * vp.cssHeight / 2

  const topLeftPdf = overlayToPdf(overlayX - halfWPx, overlayY - halfHPx, page, vp)
  const { width, height } = overlayDimensionsToPdf(defaultW, defaultH, vp)

  const raw = {
    x: topLeftPdf.x,
    y: topLeftPdf.y - height,
    width,
    height,
    page,
  }

  const clamped = clampToPdfPage(raw, vp)

  const field = addField({
    type: fieldTypeId,
    rect: clamped,
    signerId: activeSignerIdForPalette.value,
    required: false,
  })

  selectedFieldId.value = field.id
  startEditing()
})

dragEngine.on('field-move-commit', ({ fieldId, rect }) => {
  if (!currentViewport.value) return
  const vp = currentViewport.value
  const topLeftPdf = overlayToPdf(rect.x, rect.y, rect.page, vp)
  const { width, height } = overlayDimensionsToPdf(rect.width, rect.height, vp)
  const pdfRect = clampToPdfPage(
    { x: topLeftPdf.x, y: topLeftPdf.y - height, width, height, page: rect.page },
    vp,
  )
  moveField(fieldId, pdfRect)
})

dragEngine.on('field-resize-commit', ({ fieldId, rect }) => {
  if (!currentViewport.value) return
  const vp = currentViewport.value
  const topLeftPdf = overlayToPdf(rect.x, rect.y, rect.page, vp)
  const { width, height } = overlayDimensionsToPdf(rect.width, rect.height, vp)
  const pdfRect = clampToPdfPage(
    { x: topLeftPdf.x, y: topLeftPdf.y - height, width, height, page: rect.page },
    vp,
  )
  updateField({ id: fieldId, changes: { rect: pdfRect } })
})

// ── PDF loading ───────────────────────────────────────────────────────────

watch(
  () => props.pdf,
  async (pdf) => {
    if (!pdf) return
    await load()
  },
  { immediate: true },
)

function onPageCount(count: number) {
  setPageCount(count)
}

function onViewportReady(viewport: RenderPageResult['viewport']) {
  currentViewport.value = viewport
}

// ── Keyboard shortcuts ────────────────────────────────────────────────────

function handleKeydown(e: KeyboardEvent) {
  const meta = e.metaKey || e.ctrlKey

  if (meta && e.key === 'z' && !e.shiftKey) {
    e.preventDefault()
    undo()
  } else if (meta && (e.key === 'y' || (e.key === 'z' && e.shiftKey))) {
    e.preventDefault()
    redo()
  } else if (e.key === 'Delete' || e.key === 'Backspace') {
    if (selectedFieldId.value && props.mode === 'prepare') {
      e.preventDefault()
      deleteField(selectedFieldId.value)
      selectedFieldId.value = null
    }
  } else if (e.key === 'ArrowLeft') {
    if (currentPage.value > 0) currentPage.value--
  } else if (e.key === 'ArrowRight') {
    if (currentPage.value < pageCount.value - 1) currentPage.value++
  }
}

onMounted(() => window.addEventListener('keydown', handleKeydown))
onUnmounted(() => window.removeEventListener('keydown', handleKeydown))

// ── Toolbar actions ───────────────────────────────────────────────────────

function onSave() {
  const template = buildTemplate()
  emit('template-ready', template)
}

async function onSubmit() {
  if (!controller.pdfBytes) return

  try {
    const exporter = new PdfExporter()
    const auditTrail = (controller as unknown as { _auditTrail: AuditEntry[] })._auditTrail ?? []
    const partial = {
      template: props.template ?? buildTemplate(),
      completedValues: controller.completedValues,
      auditTrail,
      completedAt: new Date().toISOString(),
    }
    const { pdfBytes } = await exporter.export(
      controller.pdfBytes,
      partial.template,
      partial,
      controller.completedValues,
      { includeAuditPage: props.includeAuditPage },
    )
    await submit(pdfBytes)
  } catch (err) {
    emit('error', {
      message: err instanceof Error ? err.message : String(err),
      cause: err,
    })
  }
}

function onFieldSelect(fieldId: string) {
  if (props.mode === 'prepare') {
    selectedFieldId.value = fieldId
  } else if (props.mode === 'sign') {
    const field = fields.value.find((f) => f.id === fieldId)
    if (!field) return
    if (field.type === 'signature' || field.type === 'initials') {
      pendingSignatureFieldId.value = fieldId
      showSignatureModal.value = true
    }
  }
}

function onFieldDelete(fieldId: string) {
  deleteField(fieldId)
  if (selectedFieldId.value === fieldId) selectedFieldId.value = null
}

function onSignatureConfirm(dataUrl: string) {
  if (!pendingSignatureFieldId.value) return
  completeField(pendingSignatureFieldId.value, dataUrl)
  completedFieldIds.value = [...completedFieldIds.value, pendingSignatureFieldId.value]
  showSignatureModal.value = false
  pendingSignatureFieldId.value = null
}

function onDecline() {
  decline()
  emit('declined', {
    signerId: controller.activeSigner?.id ?? '',
    reason: '',
    timestamp: new Date().toISOString(),
  })
}

function onFieldUpdate(payload: { id: string; changes: Partial<Omit<FieldDef, 'id'>> }) {
  updateField({ id: payload.id, changes: payload.changes })
}

function onPanelDelete(fieldId: string) {
  deleteField(fieldId)
  selectedFieldId.value = null
}

function onPanelClose() {
  selectedFieldId.value = null
}
</script>

<template>
  <div
    ref="rootEl"
    class="pdf-sign-root flex h-full w-full flex-col overflow-hidden"
    data-pdf-sign
  >
    <!-- Toolbar -->
    <ToolBar
      :current-page="currentPage"
      :total-pages="pageCount"
      :scale="viewerRef?.currentScale ?? 1"
      :can-undo="canUndo"
      :can-redo="canRedo"
      :is-rendering="viewerRef?.isRendering ?? false"
      :mode="props.mode"
      :signers="displaySigners"
      :active-signer-id="activeSignerIdForPalette"
      @prev-page="currentPage = Math.max(0, currentPage - 1)"
      @next-page="currentPage = Math.min(pageCount - 1, currentPage + 1)"
      @zoom-in="viewerRef?.zoomIn()"
      @zoom-out="viewerRef?.zoomOut()"
      @fit-width="viewerRef?.fitWidth()"
      @undo="undo"
      @redo="redo"
      @save="onSave"
      @submit="onSubmit"
    >
      <template #extra>
        <slot name="toolbar-extra" />
      </template>
    </ToolBar>

    <!-- Main body -->
    <div class="flex min-h-0 flex-1 overflow-hidden">
      <!-- Palette (prepare mode only) -->
      <FieldPalette
        v-if="mode === 'prepare'"
        :signers="displaySigners"
        :active-signer-id="activeSignerIdForPalette"
        :drag-engine="dragEngine"
        @signer-change="(id) => { activeSignerIdForPalette = id }"
      />

      <!-- PDF viewer + overlay -->
      <PdfViewer
        ref="viewerRef"
        :pdf-bytes="controller.pdfBytes"
        :current-page="currentPage"
        :fields="fields"
        :signers="displaySigners"
        :drag-engine="dragEngine"
        :selected-field-id="selectedFieldId"
        :mode="props.mode"
        :completed-field-ids="completedFieldIds"
        @page-count="onPageCount"
        @viewport-ready="onViewportReady"
        @field-select="onFieldSelect"
        @field-delete="onFieldDelete"
        @zoom-change="(_s) => {}"
      />

      <!-- Field properties panel (prepare mode, field selected) -->
      <FieldPropertiesPanel
        v-if="props.mode === 'prepare'"
        :field="selectedField"
        :signers="displaySigners"
        @update="onFieldUpdate"
        @delete="onPanelDelete"
        @close="onPanelClose"
      />

      <!-- Sign-mode side panel -->
      <div
        v-if="mode === 'sign'"
        class="
          flex w-60 shrink-0 flex-col border-l
          border-[var(--psign-border)]
          bg-[var(--psign-palette-bg)]
          p-4
        "
      >
        <div class="mb-4">
          <div class="mb-1 flex items-center justify-between">
            <span class="text-xs font-medium text-[var(--psign-text)]">Progress</span>
            <span class="text-xs text-[var(--psign-text-muted)]">
              {{ Math.round(signingProgress * 100) }}%
            </span>
          </div>
          <div class="h-1.5 w-full overflow-hidden rounded-full bg-[var(--psign-border)]">
            <div
              class="h-full rounded-full bg-[var(--psign-primary)] transition-all duration-300"
              :style="{ width: `${signingProgress * 100}%` }"
            />
          </div>
        </div>

        <div class="flex-1 overflow-y-auto">
          <p class="mb-2 text-xs font-semibold uppercase tracking-widest text-[var(--psign-text-muted)]">
            Fields to complete
          </p>
          <div
            v-for="field in pendingFields()"
            :key="field.id"
            :class="[
              'mb-1 rounded-[var(--psign-radius-sm)] border px-3 py-2 text-xs',
              'border-[var(--psign-border)]',
              'bg-[var(--psign-surface)]',
              field.required
                ? 'border-l-2 border-l-[var(--psign-danger)]'
                : '',
              'cursor-pointer transition-colors hover:bg-[var(--psign-surface-raised)]',
            ]"
            @click="currentPage = field.rect.page; onFieldSelect(field.id)"
          >
            <span class="font-medium text-[var(--psign-text)]">{{ field.label }}</span>
            <span v-if="field.required" class="ml-1 text-[var(--psign-danger)]">*</span>
            <span class="ml-1 text-[var(--psign-text-muted)]">p.{{ field.rect.page + 1 }}</span>
          </div>
          <p
            v-if="pendingFields().length === 0"
            class="text-xs text-[var(--psign-success)]"
          >
            All fields complete ✓
          </p>
        </div>

        <button
          class="
            mt-4 rounded-[var(--psign-radius-sm)] border
            border-[var(--psign-border)]
            py-2 text-xs
            text-[var(--psign-danger)]
            transition-colors
            hover:bg-[var(--psign-field-required)]
            focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--psign-focus-ring)]
          "
          @click="onDecline"
        >
          Decline to sign
        </button>
      </div>
    </div>

    <!-- Loading overlay -->
    <div
      v-if="isLoading"
      class="absolute inset-0 flex items-center justify-center bg-[var(--psign-overlay)]"
      :style="{ zIndex: 200 }"
    >
      <div class="flex flex-col items-center gap-3">
        <svg class="h-8 w-8 animate-spin text-[var(--psign-primary)]" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
        </svg>
        <p class="text-sm font-medium text-[var(--psign-surface)]">Loading document…</p>
      </div>
    </div>

    <!-- Error overlay -->
    <div
      v-if="hasError"
      class="absolute inset-0 flex items-center justify-center bg-[var(--psign-canvas-bg)]"
    >
      <div class="max-w-sm text-center">
        <p class="mb-1 font-medium text-[var(--psign-danger)]">Failed to load document</p>
        <p class="text-sm text-[var(--psign-text-muted)]">
          Check that the file is a valid PDF and try again.
        </p>
      </div>
    </div>

    <!-- Signature modal -->
    <SignatureModal
      :open="showSignatureModal"
      @confirm="onSignatureConfirm"
      @cancel="showSignatureModal = false; pendingSignatureFieldId = null"
    />

    <slot />
  </div>
</template>

// packages/angular/src/components/pdf-signer.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  HostListener,
  inject,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import type {
  PdfSignOptions,
  FieldDef,
  SignerDef,
  PdfTemplate,
  SigningResult,
  ThemeTokens,
} from '@pdf-sign/core'
import {
  injectTheme,
  removeTheme,
  overlayToPdf,
  overlayDimensionsToPdf,
  clampToPdfPage,
  DragEngine,
  PdfExporter,
  initialisePdfWorker,
} from '@pdf-sign/core'
import type { RenderPageResult } from '@pdf-sign/core'
import { PdfSignService } from '../services/pdf-sign.service.js'
import { ToolbarComponent } from './toolbar.component.js'
import { PdfViewerComponent } from './pdf-viewer.component.js'
import { FieldPaletteComponent } from './field-palette.component.js'
import { FieldPropertiesPanelComponent } from './field-properties-panel.component.js'
import { SignatureModalComponent } from './signature-modal.component.js'

@Component({
  selector: 'pdf-signer',
  standalone: true,
  imports: [
    CommonModule,
    ToolbarComponent,
    PdfViewerComponent,
    FieldPaletteComponent,
    FieldPropertiesPanelComponent,
    SignatureModalComponent,
  ],
  providers: [PdfSignService],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      #rootEl
      class="pdf-sign-root flex h-full w-full flex-col overflow-hidden"
      data-pdf-sign
    >
      <!-- Toolbar -->
      <pdf-toolbar
        [currentPage]="currentPage"
        [totalPages]="svc.pageCount()"
        [scale]="viewerRef?.scale ?? 1"
        [canUndo]="svc.canUndo()"
        [canRedo]="svc.canRedo()"
        [isRendering]="viewerRef?.isRendering ?? false"
        [mode]="mode"
        [signers]="svc.signers()"
        [activeSignerId]="activeSignerIdForPalette"
        (prevPage)="prevPage()"
        (nextPage)="nextPage()"
        (zoomIn)="viewerRef?.zoomIn()"
        (zoomOut)="viewerRef?.zoomOut()"
        (fitWidth)="viewerRef?.fitWidth()"
        (undo)="svc.undo()"
        (redo)="svc.redo()"
        (save)="onSave()"
        (submitDoc)="onSubmit()"
      >
        <ng-content select="[toolbar-extra]" ngProjectAs="[toolbar-extra]"></ng-content>
      </pdf-toolbar>

      <!-- Main body -->
      <div class="flex min-h-0 flex-1 overflow-hidden">
        <!-- Palette -->
        <pdf-field-palette
          *ngIf="mode === 'prepare'"
          [signers]="svc.signers()"
          [activeSignerId]="activeSignerIdForPalette"
          [dragEngine]="dragEngine"
          (signerChange)="activeSignerIdForPalette = $event"
        />

        <!-- Viewer -->
        <pdf-viewer
          #viewerRef
          [pdfBytes]="svc.controller.pdfBytes"
          [currentPage]="currentPage"
          [fields]="svc.fields()"
          [signers]="svc.signers()"
          [dragEngine]="dragEngine"
          [selectedFieldId]="selectedFieldId"
          [mode]="mode"
          [completedFieldIds]="completedFieldIds"
          (pageCount)="svc.setPageCount($event)"
          (viewportReady)="onViewportReady($event)"
          (fieldSelect)="onFieldSelect($event)"
          (fieldDelete)="onFieldDelete($event)"
        />

        <!-- Properties panel -->
        <pdf-field-properties
          *ngIf="mode === 'prepare'"
          [field]="selectedField"
          [signers]="svc.signers()"
          (update)="svc.updateField({ id: $event.id, changes: $event.changes })"
          (delete)="onFieldDelete($event)"
          (close)="selectedFieldId = null"
        />

        <!-- Sign mode side panel -->
        <div
          *ngIf="mode === 'sign'"
          class="flex w-60 shrink-0 flex-col border-l border-[var(--psign-border)] bg-[var(--psign-palette-bg)] p-4"
        >
          <div class="mb-4">
            <div class="mb-1 flex items-center justify-between">
              <span class="text-xs font-medium text-[var(--psign-text)]">Progress</span>
              <span class="text-xs text-[var(--psign-text-muted)]">{{ progressPct }}%</span>
            </div>
            <div class="h-1.5 w-full overflow-hidden rounded-full bg-[var(--psign-border)]">
              <div
                class="h-full rounded-full bg-[var(--psign-primary)] transition-all duration-300"
                [style.width.%]="progressPct"
              ></div>
            </div>
          </div>
          <div class="flex-1 overflow-y-auto">
            <p class="mb-2 text-xs font-semibold uppercase tracking-widest text-[var(--psign-text-muted)]">Fields to complete</p>
            <div
              *ngFor="let field of pendingFieldsList"
              [class]="pendingFieldClass(field)"
              (click)="currentPage = field.rect.page; onFieldSelect(field.id)"
            >
              <span class="font-medium text-[var(--psign-text)]">{{ field.label }}</span>
              <span *ngIf="field.required" class="ml-1 text-[var(--psign-danger)]">*</span>
              <span class="ml-1 text-[var(--psign-text-muted)]">p.{{ field.rect.page + 1 }}</span>
            </div>
            <p *ngIf="pendingFieldsList.length === 0" class="text-xs text-[var(--psign-success)]">
              All fields complete ✓
            </p>
          </div>
          <button
            class="mt-4 rounded-[var(--psign-radius-sm)] border border-[var(--psign-border)] py-2 text-xs text-[var(--psign-danger)] transition-colors hover:bg-[var(--psign-field-required)]"
            (click)="onDecline()"
          >Decline to sign</button>
        </div>
      </div>

      <!-- Loading overlay -->
      <div
        *ngIf="svc.isLoading()"
        class="absolute inset-0 flex items-center justify-center bg-[var(--psign-overlay)]"
        style="z-index:200"
      >
        <div class="flex flex-col items-center gap-3">
          <svg class="h-8 w-8 animate-spin text-[var(--psign-primary)]" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/>
          </svg>
          <p class="text-sm font-medium text-[var(--psign-surface)]">Loading document…</p>
        </div>
      </div>

      <!-- Error overlay -->
      <div
        *ngIf="svc.hasError()"
        class="absolute inset-0 flex items-center justify-center bg-[var(--psign-canvas-bg)]"
      >
        <div class="max-w-sm text-center">
          <p class="mb-1 font-medium text-[var(--psign-danger)]">Failed to load document</p>
          <p class="text-sm text-[var(--psign-text-muted)]">Check that the file is a valid PDF and try again.</p>
        </div>
      </div>

      <!-- Signature modal -->
      <pdf-signature-modal
        [open]="showSignatureModal"
        (confirm)="onSignatureConfirm($event)"
        (cancel)="showSignatureModal = false; pendingSignatureFieldId = null"
      />

      <ng-content></ng-content>
    </div>
  `,
})
export class PdfSignerComponent implements OnInit, OnChanges, OnDestroy {
  @Input() pdf: PdfSignOptions['pdf'] = null
  @Input() mode: PdfSignOptions['mode'] = 'prepare'
  @Input() template?: PdfTemplate
  @Input() signerId?: string
  @Input() signers?: SignerDef[]
  @Input() theme?: Partial<ThemeTokens>
  @Input() includeAuditPage = true
  @Input() snapGrid = 0

  @Output() templateReady = new EventEmitter<PdfTemplate>()
  @Output() fieldsChanged = new EventEmitter<FieldDef[]>()
  @Output() signingComplete = new EventEmitter<SigningResult>()
  @Output() declined = new EventEmitter<{ signerId: string; reason: string; timestamp: string }>()
  @Output() exportReady = new EventEmitter<{ pdfBytes: Uint8Array; filename: string }>()
  @Output() error = new EventEmitter<{ message: string; cause?: unknown }>()

  @ViewChild('rootEl') rootElRef?: ElementRef<HTMLElement>
  @ViewChild('viewerRef') viewerRef?: PdfViewerComponent

  readonly svc = inject(PdfSignService)

  currentPage = 0
  selectedFieldId: string | null = null
  activeSignerIdForPalette: string | null = null
  viewport: RenderPageResult['viewport'] | null = null
  showSignatureModal = false
  pendingSignatureFieldId: string | null = null
  completedFieldIds: string[] = []

  dragEngine!: DragEngine
  private dragCleanups: Array<() => void> = []

  get selectedField(): FieldDef | null {
    return this.svc.fields().find((f) => f.id === this.selectedFieldId) ?? null
  }

  get progressPct(): number {
    return Math.round(this.svc.signingProgress() * 100)
  }

  get pendingFieldsList(): FieldDef[] {
    return this.svc.pendingFields()
  }

  pendingFieldClass(field: FieldDef): string {
    const base = 'mb-1 rounded-[var(--psign-radius-sm)] border px-3 py-2 text-xs border-[var(--psign-border)] bg-[var(--psign-surface)] cursor-pointer transition-colors hover:bg-[var(--psign-surface-raised)]'
    return field.required ? `${base} border-l-2 border-l-[var(--psign-danger)]` : base
  }

  ngOnInit(): void {
    initialisePdfWorker()

    this.dragEngine = new DragEngine({ gridSize: this.snapGrid })
    this.activeSignerIdForPalette = this.signers?.[0]?.id ?? 'signer-1'

    this.svc.initialise({
      mode: this.mode,
      pdf: this.pdf,
      ...(this.template !== undefined && { template: this.template }),
      ...(this.signerId !== undefined && { signerId: this.signerId }),
      ...(this.signers !== undefined && { signers: this.signers }),
      includeAuditPage: this.includeAuditPage,
    })

    const ctrl = this.svc.controller
    this.dragCleanups.push(
      ctrl.events.on('fields-changed', ({ fields }) => this.fieldsChanged.emit(fields)),
      ctrl.events.on('template-ready', ({ template }) => this.templateReady.emit(template)),
      ctrl.events.on('signing-complete', (r) => this.signingComplete.emit(r)),
      ctrl.events.on('declined', (p) => this.declined.emit(p)),
      ctrl.events.on('export-ready', (p) => this.exportReady.emit(p)),
      ctrl.events.on('error', (p) => this.error.emit(p)),
    )

    this.dragCleanups.push(
      this.dragEngine.on('palette-drop', ({ fieldTypeId, overlayX, overlayY, page }) => {
        if (!this.viewport) return
        const DEFAULT: Record<string, { w: number; h: number }> = {
          signature: { w: 180, h: 60 }, initials: { w: 80, h: 40 },
          stamp: { w: 100, h: 100 }, checkbox: { w: 20, h: 20 },
          radio: { w: 16, h: 16 }, default: { w: 150, h: 36 },
        }
        const { w, h } = DEFAULT[fieldTypeId] ?? DEFAULT['default']!
        const vp = this.viewport
        const halfWPx = (w / vp.pdfNaturalWidth) * vp.cssWidth / 2
        const halfHPx = (h / vp.pdfNaturalHeight) * vp.cssHeight / 2
        const topLeft = overlayToPdf(overlayX - halfWPx, overlayY - halfHPx, page, vp)
        const { width, height } = overlayDimensionsToPdf(w, h, vp)
        const raw = { x: topLeft.x, y: topLeft.y - height, width, height, page }
        const clamped = clampToPdfPage(raw, vp)
        const field = this.svc.addField({ type: fieldTypeId, rect: clamped, signerId: this.activeSignerIdForPalette, required: false })
        this.selectedFieldId = field.id
        this.svc.startEditing()
      }),

      this.dragEngine.on('field-move-commit', ({ fieldId, rect }) => {
        if (!this.viewport) return
        const vp = this.viewport
        const tl = overlayToPdf(rect.x, rect.y, rect.page, vp)
        const { width, height } = overlayDimensionsToPdf(rect.width, rect.height, vp)
        this.svc.moveField(fieldId, clampToPdfPage({ x: tl.x, y: tl.y - height, width, height, page: rect.page }, vp))
      }),

      this.dragEngine.on('field-resize-commit', ({ fieldId, rect }) => {
        if (!this.viewport) return
        const vp = this.viewport
        const tl = overlayToPdf(rect.x, rect.y, rect.page, vp)
        const { width, height } = overlayDimensionsToPdf(rect.width, rect.height, vp)
        this.svc.updateField({ id: fieldId, changes: { rect: clampToPdfPage({ x: tl.x, y: tl.y - height, width, height, page: rect.page }, vp) } })
      }),
    )

    if (this.pdf) void this.svc.load()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['theme'] && this.rootElRef) {
      const el = this.rootElRef.nativeElement
      if (this.theme) injectTheme(el, this.theme)
      else removeTheme(el)
    }
    if (changes['pdf'] && !changes['pdf'].firstChange && this.pdf) {
      void this.svc.load()
    }
  }

  ngOnDestroy(): void {
    this.dragCleanups.forEach((fn) => fn())
    this.dragEngine.destroy()
  }

  onViewportReady(vp: RenderPageResult['viewport']): void {
    this.viewport = vp
  }

  onFieldSelect(fieldId: string): void {
    if (this.mode === 'prepare') {
      this.selectedFieldId = fieldId
    } else if (this.mode === 'sign') {
      const field = this.svc.fields().find((f) => f.id === fieldId)
      if (!field) return
      if (field.type === 'signature' || field.type === 'initials') {
        this.pendingSignatureFieldId = fieldId
        this.showSignatureModal = true
      }
    }
  }

  onFieldDelete(fieldId: string): void {
    this.svc.deleteField(fieldId)
    if (this.selectedFieldId === fieldId) this.selectedFieldId = null
  }

  onSignatureConfirm(dataUrl: string): void {
    if (!this.pendingSignatureFieldId) return
    this.svc.completeField(this.pendingSignatureFieldId, dataUrl)
    this.completedFieldIds = [...this.completedFieldIds, this.pendingSignatureFieldId]
    this.showSignatureModal = false
    this.pendingSignatureFieldId = null
  }

  async onSubmit(): Promise<void> {
    const ctrl = this.svc.controller
    if (!ctrl.pdfBytes) return
    try {
      const exporter = new PdfExporter()
      const tmpl = this.template ?? this.svc.buildTemplate()
      const { pdfBytes } = await exporter.export(
        ctrl.pdfBytes, tmpl,
        { template: tmpl, completedValues: ctrl.completedValues, auditTrail: [], completedAt: new Date().toISOString() },
        ctrl.completedValues,
        { includeAuditPage: this.includeAuditPage },
      )
      await this.svc.submit(pdfBytes)
    } catch (err) {
      this.error.emit({ message: err instanceof Error ? err.message : String(err), cause: err })
    }
  }

  onSave(): void {
    const t = this.svc.buildTemplate()
    this.templateReady.emit(t)
  }

  onDecline(): void {
    this.svc.decline()
    this.declined.emit({ signerId: this.svc.controller.activeSigner?.id ?? '', reason: '', timestamp: new Date().toISOString() })
  }

  prevPage(): void { if (this.currentPage > 0) this.currentPage-- }
  nextPage(): void { if (this.currentPage < this.svc.pageCount() - 1) this.currentPage++ }

  @HostListener('keydown', ['$event'])
  onKeydown(e: KeyboardEvent): void {
    const meta = e.metaKey || e.ctrlKey
    if (meta && e.key === 'z' && !e.shiftKey) { e.preventDefault(); this.svc.undo() }
    else if (meta && (e.key === 'y' || (e.key === 'z' && e.shiftKey))) { e.preventDefault(); this.svc.redo() }
    else if ((e.key === 'Delete' || e.key === 'Backspace') && this.selectedFieldId && this.mode === 'prepare') {
      e.preventDefault(); this.onFieldDelete(this.selectedFieldId)
    } else if (e.key === 'ArrowLeft') this.prevPage()
    else if (e.key === 'ArrowRight') this.nextPage()
  }
}
